### ISSUE TITLE
setError problems (or misusage)

### ISSUE THREAD

**Issue by rkurbatov** [bluebill1049/react-hook-form#140]
First of all thanks for the great library!

We were using redux-forms intensively in our current project and now want to switch to hooks based solution. Yours works perfectly for most of the cases but there are still some things that require rethinking.

There was a special type of error thrown in submit handlers called `SubmissionError`. The object passed to it allowed setting an error of some type in case submit action failed. I tried to repeat that behavior but got a problem with `setError`. If I set error state for any existing field (or non-existing submission filed) I see that `errors` object in the form is changed accordingly but then rerender occurs (probably after validation?) and it returns to the previous empty state.

I use something like this:

```
export const withSubmissionErrorHandler = (
  onSubmit: Function,
  setError: SetError,
) => {
  return async (...args) => {
    try {
      await onSubmit(...args)
    } catch (err) {
      if (err instanceof SubmissionError) {
        setError('submission', 'submission', err.submissionMessage)
      }
    }
  }
}
```

that is used in form 
```
<form
      onSubmit={handleSubmit(withSubmissionErrorHandler(onSubmit, setError))}
    >
```

and throw custom error in `onSubmit` method passed to the form.

Is there any better solution for that? Or how can I fix setError behavior? Or could it be I use it in a wrong way?

Thanks in advance.

**Comment by bluebill1049** [comment]
Could u please provide a code sandbox? I could investigate into

**Comment by bluebill1049** [comment]
looks like this is a bug.

**Comment by bluebill1049** [comment]
could you please try this version? `react-hook-form@3.18.9-beat.1`

**Comment by bluebill1049** [comment]
FYI for a custom Error message, you will have to `clearError` for success data
```
  try {
      await onSubmit(...args)
      clearError('submission')
    } catch (err) {
      if (err instanceof SubmissionError) {
        setError('submission', 'submission', err.submissionMessage)
      }
    }
```

**Comment by bluebill1049** [comment]
fixed and published: https://github.com/bluebill1049/react-hook-form/releases/tag/3.18.9

**Comment by rkurbatov** [comment]
Wow! Thank you!

**Comment by bluebill1049** [comment]
thank you for report the issue @rkurbatov 🥃

**Comment by rkurbatov** [comment]
Ehm... Just get to work and run the code with the new version - the problem remains. I'll try to create a simplified sandbox right now.

**Comment by bluebill1049** [comment]
i tested with the following:

https://codesandbox.io/s/react-hook-form-basic-n53gm

**Comment by rkurbatov** [comment]
And here is my example: https://codesandbox.io/s/seterror-problems-60ghf

errors object becomes empty again after the error

**Comment by bluebill1049** [comment]
taking a look your example now

**Comment by bluebill1049** [comment]
try this https://codesandbox.io/s/seterror-problems-hqhpo @rkurbatov

**Comment by rkurbatov** [comment]
Works now!

**Comment by bluebill1049** [comment]
published! thank you :)

**Comment by rkurbatov** [comment]
Can we have something similar in the library? It would be nice to set error messages in the same manner:

```
throw new SumbissionError({ fieldname: 'message' })
```

in the onSubmit handler and some special `handleSubmit` version (or even modified one) without need to pass setError/clearError every time?

**Comment by bluebill1049** [comment]
at the moment, react hook form doesn't have any `throw` API, curious the difference between `setError` vs `throw new Error`. Normally you wouldn't need `clearError`, probably only use it during async submission.

**Comment by rkurbatov** [comment]
So what about that approach? If `SubmissionError` was thrown by `onSubmit`, `handleSubmit` catches that and sets errors internally according to error object?

**Comment by bluebill1049** [comment]
Yea, I understand where you coming from: which are the all the goodies from `redux-form`.
but to be honest, I don't plan to implement `throw` errors at this stage. I am not seeing the value of throw error for submitting at validation that much (at this stage) and personally, I prefer to keep the API simple and primitive, however, I am open to changes if more people request similar features request.

**Comment by bluebill1049** [comment]
@rkurbatov you happy to close this issue for now? 🙏

**Comment by rkurbatov** [comment]
Oh, sure. Thanks!
