### ISSUE TITLE
自定义组件的校验问题 custom register validation

### ISSUE THREAD

**Issue by crabkiller** [bluebill1049/react-hook-form#164]
你好，请教一下，如果给自定义组件传 `register` 和 `setValue` 方法来让 `react-hook-form` 来接管数据绑定的工作，此时如果我还需要添加校验的话，是需要把校验规则(比如 `validateProps`)也传给自定义组件，在自定义组件内 `register({ name: 'xxx', ...validateProps })` 这样使用么，感觉这样的话内部组件需要知道太多上层组件的信息了，有没有推荐的比较好的解决方案，非常感谢🙏

English summary: what's the best practice to handle custom register validation?

**Comment by bluebill1049** [comment]
你好 我会建议如下：
Hi, I will recommend the following for custom `register`:

https://react-hook-form.com/api#setValue
https://react-hook-form.com/api#triggerValidation

```
register({ name: 'test' }, { validate: yourFunction, required: true })

<CustomComponent onChange={(val) => {
  setValue('test', val, true); // third argument will trigger validation 
}} />

// same as above
<CustomComponent onChange={(val) => {
  setValue('test', val);
  triggerValidation();
}} />
```

**Comment by crabkiller** [comment]
Thank you for your nice suggestion. But I got some other problems followed by this pattern.
1. I can't get `defaultValue` in my `CustomComponent` which is defined in `useForm({ defaultValues: { ... } })`, so I should pass `defaultValue` manually like this `<CustomComponent defaultValue={defaultValue} />`, yeah?
2. And I also think maybe this pattern is not so convenient. I must define a `onChange` method in all places where my `CustomComponent` be used. Using the `useImperativeHandle` hook in my `CustomComponent` may be a better solution I think. Just like this example: https://github.com/bluebill1049/react-hook-form/issues/36.
```
...

const SplitInput = forwardRef((props: Props, ref: any) => {
  const [value, setValue] = useState(maybeDefaultValue);

  useImperativeHandle(
    ref,
    () => {
      return {
        type: "custom-type",
        name: props.name,
        value: value.join("")
      };
    },
    [value]
  );
});

...
```
Maybe `react-hook-form` can get value from my custom `ref` automatically, and achieve his own staff then. I have tried this but got an error throw by `findRemovedFieldAndRemoveListener` method in the line `const isRefDeleted = !document.body.contains(ref);` because of my custom `ref` is not a `Node`. And the `defaultValue` problem mentioned above also exitted with this pattern.

My English is poor, so if I confused you please tell me, I can give a Chinese version of this.

Thanks again for your great contributions.

**Comment by bluebill1049** [comment]
Your English is perfect 👍 totally make sense

> I can't get defaultValue in my CustomComponent which is defined in useForm({ defaultValues: { ... } }), so I should pass defaultValue manually like this <CustomComponent defaultValue={defaultValue} />, yeah?

Question: do you custom component contains `ref`? 

why not just 
`<CustomComponent register={register} /> // you can do foward ref as well `

inside render:
```
<div>
  <input ref={register} name="test" />
</div>

```

then you don't need to set `defaultValue` manually.

> And I also think maybe this pattern is not so convenient. I must define a onChange method in all places where my CustomComponent be used. Using the useImperativeHandle hook in my CustomComponent may be a better solution I think. Just like this example: #36.

if you can do the above, then this should be solved automatically.

-----------------

however, if your custom component doesn't contain any `ref`, then you need to use `onChange` with `setValue` which is going back to the controlled component pattern.

hope these make sense.

**Comment by crabkiller** [comment]
> Question: do your custom component contains ref?
>
> if so, why not just
> `<CustomComponent register={register} /> // you can do foward ref as well`
>
> inside render:
>
> `<div><input ref={register} name="test" /></div>`
> then you don't need to set defaultValue manually.


Yes, my custom component contains ref, but I also need `defaultValue` to render other contents in my `CustomComponent`.

For example:

```
// ...

function MyUniqueSelect(props) {
  const {
    options,
    onChange,
  } = props;

  const [value, setValue] = useState(needDefaultValueHere);
  const label = useMemo(() => (
    (options.find(option => option.value === value) || {}).label
  ), [value]);

  const handleChange = useCallback((e) => {
    const newValue = e.target.value;
    setValue(newValue);
    onChange(newValue);
  }, []);

  return (
    <div>
      <span>{label}</span>
      {
        options.map(option => (
          <input
            type="radio"
            name="whatever_name"
            value={option.value}
            checked={option.value === value}
            onClick={handleChange}
          />
        ))
      }
    </div>
  );
}

const options = [{
  label: 'lable1',
  value: 'value1',
}, {
  label: 'lable2',
  value: 'value2',
}];
const {
  register,
  setValue,
} = useForm({
  defaultValues: {
    test: options[0].value, // or options[0], prefer options[0].value
  },
});
register({ name: 'test' }, { validate: yourFunction, required: true });

<MyUniqueSelect
  options={options}
  onChange={(val) => {
    setValue('test', val, true); // third argument will trigger validation 
  }}
/>

// ...
```

Just like this example, I need `defaultValue` to render `label` field not just bind the `value` to some native HTML form tag.

**Comment by bluebill1049** [comment]
I think the problem is where are you `register`.

`register` should be inside of your `<MyUniqueSelect />`

```
<input
  type="radio"
  name="whatever_name"
  ref={register({  required: true })}
/>
```

**Comment by crabkiller** [comment]
This will go back to my original question:

>你好，请教一下，如果给自定义组件传 register 和 setValue 方法来让 react-hook-form 来接管数据绑定的工作，此时如果我还需要添加校验的话，是需要把校验规则(比如 validateProps)也传给自定义组件，在自定义组件内 register({ name: 'xxx', ...validateProps }) 这样使用么，感觉这样的话内部组件需要知道太多上层组件的信息了

>English summary: If I `register` the field inside my custom component, I must transfer `validateProps` into the custom component manually like this `<MyUniqueSelect validateProps={validateProps} />`, so then I can do `ref={register(validateProps)}` in my custom component. I think this is not nice because the custom component needs to know so many information which is upper component's logic. My custom component just needs to render the UI originally.

I'm also an [`ant-design`](https://ant.design/components/form/#components-form-demo-customized-form-controls) user, I think maybe his `props: { value, onChange }` way is a simple pattern for me to build my custom component. But he uses HOC to achieve this I know.

And even if I `register` inside my custom component, I still don't know how to render my `label` field elegantly. Should I `watch('upper_name')` in `MyUniqueSelect` to get the `value` and then compute `label` field.

**Comment by crabkiller** [comment]
Thanks again for your patient answer.

**Comment by bluebill1049** [comment]
That's not a problem at all, I think I need to clearly understand what you try to achieve in order to help you efficiently. 

1. what type of component you try to build?
2. do you need to dynamically change `label` while user input changes?

**Comment by crabkiller** [comment]
>1. what type of component you try to build?

I'm trying to build a `Select` component just like above.

>2. do you need to dynamically change label while user input changes?

Yes.

The `Select` component contains a `label` field to show the user-friendly content which user select, and a list of `radio`s so that user can change his/her selection. The `radio`'s `value` prop is binded to a `value` field which is then submitted to server. So when user checks a new `radio`, the `label` field should update to a new one which is refer to the `value`. And also the `label` field should render a correct content refer to the `defaultValue` when `Select` is inited. I think the main problem is that `react-hook-form` just reactives the `value` which is bind to the native HTML form tag, I can't handle the `value` myself so that I can do some stuffs with the `value`, such as render `label` field in this `Select`. Except I inject many `react-hook-form`'s methods from upper component. But I think this will makes my `Select` having too much dependency with `react-hook-form` and this is not what my `Select` should sense.

**Comment by crabkiller** [comment]
<img width="531" alt="111111" src="https://user-images.githubusercontent.com/4629430/62111847-18362500-b2e4-11e9-9f68-8efdf0c0b4c3.png">

It looks like this.

**Comment by bluebill1049** [comment]
Post ur code as well please

**Comment by crabkiller** [comment]
```
// ...

function MyUniqueSelect(props) {
  const {
    options,
    onChange,
  } = props;

  const [value, setValue] = useState(needDefaultValueHere);
  const label = useMemo(() => (
    (options.find(option => option.value === value) || {}).label
  ), [value]);

  const handleChange = useCallback((e) => {
    const newValue = e.target.value;
    setValue(newValue);
    onChange(newValue);
  }, []);

  return (
    <div>
      <span>{label}</span>
      {
        options.map(option => (
          <input
            type="radio"
            name="whatever_name"
            value={option.value}
            checked={option.value === value}
            onClick={handleChange}
          />
        ))
      }
    </div>
  );
}

const options = [{
  label: 'lable1',
  value: 'value1',
}, {
  label: 'lable2',
  value: 'value2',
}];
const {
  register,
  setValue,
} = useForm({
  defaultValues: {
    test: options[0].value, // or options[0], prefer options[0].value
  },
});
register({ name: 'test' }, { validate: yourFunction, required: true });

<MyUniqueSelect
  options={options}
  onChange={(val) => {
    setValue('test', val, true); // third argument will trigger validation 
  }}
/>

// ...
```

**Comment by bluebill1049** [comment]
https://codesandbox.io/s/react-hook-form-basic-904jh

I think this is what you after.

**Comment by crabkiller** [comment]
Thanks very much for your patience and such awesome codes. I will close this issue and hope these codes will help others who got similar problem.

**Comment by bluebill1049** [comment]
hopefully, it was the answer u seek for 👍 please share around the community in China (if u find it useful and star this open-source project to support) ❤️
